config/routes.rb
Rails.application.routes.draw do
  root "homepage#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # resources :articles, only: [:show, :index, :new, :create,:edit, :update,:destroy]
  resources :articles
  resources :products
  resources :sales
  get "signup", to: "users#new"
  resources :users, except: [:new]
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  resources :categories
  resources :product_lists
  resources :shipments
  resources :vendors
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true
  validates :text, presence: true
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  validates_uniqueness_of :name
  has_many :article_categories
  has_many :articles, through: :article_categories
  has_many :products
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :product_histories
  has_many :product_vendors
  has_many :vendors, through: :product_vendors

  def self.filter(params)
    if params.length > 3
      puts "filtered"
      params.slice(0, params.length - 3)
      products = Category.find_by(name: "Frozen").products
      return products
    else
      puts "all"
      products = Product.all
      return products
    end
  end

  def barcode=(value)
    if value.length == 12
      write_attribute(:barcode, value.insert(0, "0"))
    else
      write_attribute(:barcode, value)
    end
  end

   def self.to_csv
    attributes = %w{id name quantity_in_total}

    CSV.generate(headers: true) do |csv|
      csv << attributes

      all.each do |user|
        csv << attributes.map{ |attr| user.send(attr) }
      end
    end
  end

   
end

app/models/product_history.rb
class ProductHistory < ApplicationRecord
  belongs_to :product
end

app/models/product_list.rb
class ProductList < ApplicationRecord
   
end

app/models/product_vendor.rb
class ProductVendor < ApplicationRecord
  belongs_to :product
  belongs_to :vendor
end

app/models/sale.rb
class Sale < ApplicationRecord
  validates :data, presence: true
end

app/models/shipment.rb
class Shipment < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  has_many :articles, dependent: :destroy
  validates :username, presence: true, length: { minimum: 3, maximum: 25 }, uniqueness: { case_sensitive: false }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 105 }, uniqueness: { case_sensitive: false }, format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/models/vendor.rb
class Vendor < ApplicationRecord
  has_many :product_vendors
  has_many :products, through: :product_vendors
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :require_admin, except: [:index, :show]

  def new
    @category = Category.new
  end

  def index
    @categories = Category.all.order(:name)
  end

  def show
    @category = Category.find(params[:id])

    @products = @category.products.order(:updated_at).reverse_order
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Category was successfully created"
      redirect_to @category
    else
      render "new"
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:notice] = "Category name updated successfully"
      redirect_to @category
    else
      render "edit"
    end
  end

  def destroy
    @category = Category.find(params[:id])
    if @category.destroy
      flash[:notice] = @category.name.to_s + "was deleted successfully"
      redirect_to categories_path
    else
      flash[:alert] = "Something went wrong"
      redirect_to(:back)
    end
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    if !(logged_in? && current_user.admin?)
      flash[:alert] = "Only admin can perform that action"
      redirect_to categories_path
    end
  end
end

app/controllers/sales_controller.rb
require "csv"

class SalesController < ApplicationController
  before_action :set_sale, only: [:update, :show, :destroy]

  @@addSale = "addSale"
  @@deleteSale = "deleteSale"

  def index
    @sales = Sale.all.order(:date)
  end

  def new
    @sale = Sale.new
  end

  def create
    saleData = parseCSVFileToArray(sales_params[:data])
    saleDate = sales_params[:date]
    @sale = Sale.new(date: saleDate, data: saleData)
    if @sale.save
      flash[:notice] = "Sale data was uploaded successfully"
      redirect_to @sale
    else
      render "new"
    end
  end

  def show
  end

  def update
    if !@sale.is_confirm
      @sale.update(is_confirm: true)
      updateProductsQuantity(@sale, @@addSale)
      flash[:notice] = "Data confirmed. Quantity had been updated"
      redirect_to @sale
    else
      updateProductsQuantity(@sale, @@deleteSale)
      redirect_to sales_path
    end
  end

  def destroy
    if @sale.is_confirm
      if @sale.destroy
        updateProductsQuantity(@sale, @@deleteSale)
        flash[:notice] = "Sale was deleted successfully"
        redirect_to sales_path
      else
        flash[:alert] = "Something went wrong"
        redirect_to(:back)
      end
    else
      if @sale.destroy
        flash[:notice] = "Sale was deleted successfully"
        redirect_to sales_path
      else
        flash[:alert] = "Something went wrong"
        redirect_to(:back)
      end
    end
  end

  private

  def set_sale
    @sale = Sale.find(params[:id])
  end

  def sales_params
    params.require(:sale).permit(:date, :data)
  end

  def parseCSVFileToArray(csv)
    CSV.parse(csv.read).drop(1)
  end

  def addInstanceId(product, instancd_id)
    if product.instance_id.nil?
      product.update(instance_id: instancd_id)
    end
  end

  def updateProductsQuantity(sale, type)
    if type == @@addSale
      sale.data.each do |product|
        findedProduct = Product.find_by(name: product[2])
        if findedProduct
          addInstanceId(findedProduct, product[0])
          findedProduct.update(quantity_in_total: findedProduct.quantity_in_total - product[4].to_i)
        end
      end
    elsif type == @@deleteSale
      sale.data.each do |product|
        finded = Product.find_by(name: product[2])
        if finded
          finded.update(quantity_in_total: finded.quantity_in_total + product[4].to_i)
        end
      end
    else
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = { size: 80 })
    email_address = user.email
    hash = Digest::MD5.hexdigest(email_address)
    size = options[:size]
    image_src = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(image_src, alt: user.username, class: "rounded mx-auto d-block shadow")
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/shipments_helper.rb
module ShipmentsHelper
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category), class: "badge badge-pill badge-info mr-1" %>

app/views/categories/_form.html.erb
<%= form_with(model: @category, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |form| %>
<div class="form-group row">
  <%= form.label :name, "Category name", class: "col-2 col-form-label text-light" %>
  <div class="col-10">
   <%= form.text_field :name, class: "form-control shadow rounded", placeholder: "Enter an name" %>
  </div>
</div>
  
 
 
<div class="form-group row justify-content-center">
    <%= form.submit class: "btn btn-outline-light btn-lg" %>
</div>
<% end %>

app/views/categories/edit.html.erb
<h1 class="text-center mt-4">Edit category</h1>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-10">
            <%= render "shared/errors", obj: @category %>
            <%= render "form" %>
        </div>
        <div>
        <%= link_to "[ Cancel and return to category ]", category_path(@category), class: "text-info" %>
        </div>
            
    </div>
</div>

app/views/categories/index.html.erb
<div class="pl-2 pr-2">

<div class="d-flex justify-content-between align-items-center">
<h1>Categories</h1>
<div class="d-flex ">
<%= link_to "New category", new_category_path, class: "btn btn-outline-info mr-2" %>
<%= link_to "Back to homepage", root_path, class: "btn btn-outline-secondary" %>
</div>
</div>




<table class="table">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Product Count</th>
      <th scope="col">Updated Date</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
  <% @categories.each do |category| %>
    <tr>
      <th scope="row"><%= link_to category.name, category_path(category), class: "text-success" %></th>
      <td><%= pluralize(category.products.count, "product") %></td>
      <td><%= category.updated_at.strftime("%m/%d/%Y") %></td>
      <td><%= link_to "Edit", edit_category_path(category), class: "btn btn-outline-info text-center btn-sm " %>
    <%= link_to "Delete", category_path(category), class: "btn btn-outline-danger text-center btn-sm ", method: :delete, data: { confirm: "Are you sure?" } %></td>
    </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/categories/new.html.erb
<h1 class="text-center mt-4">Create category</h1>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-10">
            <%= render "shared/errors", obj: @category %>
            <%= render "form" %>
        </div>
        <div>
        <%= link_to "[ Cancel and return to categories listing ]", categories_path, class: "text-info" %>
        </div>
            
    </div>
</div>

app/views/categories/show.html.erb
<div class="pl-2 pr-2">
<div class="d-flex justify-content-between align-items-center">
<h1><%= @category.name %></h1>
<div class="d-flex justify-content-end align-items-center">
<% if logged_in? && current_user.admin? %>
<%= link_to "Edit category", edit_category_path(@category), class: "btn btn-outline-info mr-2" %>
<%= link_to "Delete category", category_path(@category), method: :delete, class: "btn btn-outline-danger mr-2" %>
<% end %>
<%= link_to "Back to categories", categories_path, class: "btn btn-outline-secondary" %>
</div >

</div>
</div>




<div class="pl-5 pr-5">
<table class="table table-striped table-bordered table-light">
  <thead>
    <tr>
      <th scope="col">Instance_id</th>
      <th scope="col">Name</th>
      <th scope="col">Foreign Name</th>
      <th scope="col">Barcode</th>
      <th scope="col">Quantity</th>
      <th scope="col">Vendors</th>
      <th scope="col">Expiration Date</th>
      <th scope="col">Updated Date</th>

      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
  <% @products.each do |product| %>
    <tr>
    <td><%= product.instance_id %></td>
      <td class="text-capitalize"><%= link_to product.name, product_path(product) %></td>
      <td><%= product.foreign_name %></td>
      <td><%= product.barcode %></td>
      <td><%= product.quantity_in_total %></td>
      <% if product.vendors.any? %>
              <td><%= render product.vendors %></td> 
               <% else %>
               <td></td>
            <% end %>

       <td><%= product.expiration_date.in_time_zone("America/Chicago").strftime("%m/%d/%Y") %>
      <td><%= product.updated_at.in_time_zone("America/Chicago").strftime("%m/%d/%Y - %H:%M:%S") %></td>
<td>
<%= link_to "Edit", edit_product_path(product), class: "btn btn-outline-info text-center " %>
    <%= link_to "Delete", product_path(product), class: "btn btn-outline-danger text-center ", method: :delete, data: { confirm: "Are you sure?" } %></td></td>
    </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>