config/routes.rb
Rails.application.routes.draw do
  root "homepage#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # resources :articles, only: [:show, :index, :new, :create,:edit, :update,:destroy]
  resources :articles
  resources :products
  resources :sales
  get "signup", to: "users#new"
  resources :users, except: [:new]
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  resources :categories
  resources :product_lists
  resources :shipments
  resources :vendors
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :product_histories
  has_many :product_vendors
  has_many :vendors, through: :product_vendors

  def self.filter(params)
    if params.length > 3
      puts "filtered"
      params.slice(0, params.length - 3)
      products = Category.find_by(name: "Frozen").products
      return products
    else
      puts "all"
      products = Product.all
      return products
    end
  end

  def barcode=(value)
    if value.length == 12
      write_attribute(:barcode, value.insert(0, "0"))
    else
      write_attribute(:barcode, value)
    end
  end

   def self.to_csv
    attributes = %w{id name quantity_in_total}

    CSV.generate(headers: true) do |csv|
      csv << attributes

      all.each do |user|
        csv << attributes.map{ |attr| user.send(attr) }
      end
    end
  end

   
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :require_user, except: [:index, :show]
  before_action :set_product, only: [:update, :edit, :destroy]

  def new
    @product = Product.new
  end

  def index
    @products = Product.all.includes(:category, :vendors).order(:updated_at).reverse_order
  end

  def create
    @product = Product.new(product_params.except("quantity_per_box", "quantity_of_box"))
    if !@product.quantity_in_total
      @product.quantity_in_total = product_params[:quantity_per_box].to_i * product_params[:quantity_of_box].to_i
    end

    if @product.save
      flash[:notice] = "product was created successfully."
      redirect_to @product
    else
      render "new"
    end
  end

  def show
    if params[:id].length >= 6
      @product = Product.find_by(barcode: params[:id])
      if @product == nil
        redirect_to root_path + "?error=true" + "&" + "barcode=" + params[:id]
      else
        redirect_to @product
      end
    else
      @product = Product.find(params[:id])
      @productHistory = @product.product_histories.order(created_at: :desc)
    end
  end

  def edit
    session[:return_to] = request.referer
  end

  def update
    oldQuantity = @product.quantity_in_total
    if @product.update(product_params.except("quantity_per_box", "quantity_of_box"))
      if oldQuantity != @product.quantity_in_total
        changedQuantity = @product.quantity_in_total - oldQuantity
        @productHistory = ProductHistory.new(change_in_quantity: changedQuantity, product: @product)
        @productHistory.save
      end

      flash[:notice] = "product was updated successfully"
      redirect_to session.delete(:return_to)
    else
      render "edit"
    end
  end

  def destroy
    if @product.destroy
      flash[:notice] = @product.name.to_s + " was deleted successfully"
      redirect_to products_path
    else
      flash[:alert] = "Something went wrong"
      redirect_to(:back)
    end
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :foreign_name, :barcode, :expiration_date, :category_id, :quantity_in_total, :quantity_per_box, :quantity_of_box, vendor_ids: [])
  end

  def store_location
    session[:return_to] = request.fullpath if request.get? and controller_name != "user_sessions" and controller_name != "sessions"
  end

  def redirect_back_or_default(default)
    redirect_to(session[:return_to] || default)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_filter.html.erb
<ul class="list-group list-group-flush">
  <li class="list-group-item">Category</li>
<%= form_with(url: products_path, method: "get") do %>
  <% Category.all.each do |category| %>
  <div class="form-check pl-4" style="font-size:1em">
    <%= check_box_tag(category.name, 1, false, class: "form-check-input") %>
      <%= label_tag(category.name, category.name, class: "form-check-label") %>
  </div>
  <% end %>
<li class="list-group-item">Quantity</li>
 <%= submit_tag "Filter", class: "btn btn-info mt-4" %>
<% end %>
</ul>

app/views/products/_form.html.erb
<div class="container">

<div class="row justify-content-center">
<div class="col-10">
<%= render "shared/errors", obj: @product %>
<%= form_with(model: @product, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |form| %>
<div class="form-group row">
  <%= form.label :name, class: "col-2 col-form-label text-light" %>
  <div class="col-10">
   <%= form.text_field :name, class: "form-control shadow rounded" %>
  </div>
</div>
<div class="form-group row">
  <%= form.label :foreign_name, class: "col-2 col-form-label text-light" %>
  <div class="col-10">
   <%= form.text_field :foreign_name, class: "form-control shadow rounded" %>
  </div>
</div>

    <div class="form-group row input-field">
        <%= form.label :barcode, class: "col-2 col-form-label text-light" %>
        <div class="col-8 pr-0">
            <%= form.text_field :barcode, class: "barcode form-control shadow rounded ", id: "isbn_input" %>
        </div>
        <div class="col-2 mt-1">
        <button type="button" class="scan button ">
        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-upc-scan" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
  <path fill-rule="evenodd" d="M1.5 1a.5.5 0 0 0-.5.5v3a.5.5 0 0 1-1 0v-3A1.5 1.5 0 0 1 1.5 0h3a.5.5 0 0 1 0 1h-3zM11 .5a.5.5 0 0 1 .5-.5h3A1.5 1.5 0 0 1 16 1.5v3a.5.5 0 0 1-1 0v-3a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 1-.5-.5zM.5 11a.5.5 0 0 1 .5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 1 0 1h-3A1.5 1.5 0 0 1 0 14.5v-3a.5.5 0 0 1 .5-.5zm15 0a.5.5 0 0 1 .5.5v3a1.5 1.5 0 0 1-1.5 1.5h-3a.5.5 0 0 1 0-1h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 1 .5-.5z"/>
  <path d="M3 4.5a.5.5 0 0 1 1 0v7a.5.5 0 0 1-1 0v-7zm2 0a.5.5 0 0 1 1 0v7a.5.5 0 0 1-1 0v-7zm2 0a.5.5 0 0 1 1 0v7a.5.5 0 0 1-1 0v-7zm2 0a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5v-7zm3 0a.5.5 0 0 1 1 0v7a.5.5 0 0 1-1 0v-7z"/>
</svg>
        </button>
        </div>
    </div>

  <div class="form-group row">
    <%= form.label :expiration_date, class: "col-2 col-form-label text-light" %>
    <div class="col-10">
    <%= form.date_field(:expiration_date, class: "form-control shadow rounded", min: Date.today, value: Date.new(2030, 1, 1)) %>
    </div>
  </div>
<div class="form-group row">
    <%= form.label :quantity_of_box, class: "col-2 col-form-label text-light" %>
    <div class="col-10">
    <%= form.number_field :quantity_of_box, class: "form-control shadow rounded" %>
    </div>
  </div>
   <div class="form-group row">
    <%= form.label :quantity_per_box, class: "col-2 col-form-label text-light" %>
    <div class="col-10">
    <%= form.number_field :quantity_per_box, class: "form-control shadow rounded" %>
    </div>
  </div>

    <div class="form-group row">
    <%= form.label :quantity_in_total, class: "col-2 col-form-label text-light" %>
    <div class="col-10">
    <%= form.number_field :quantity_in_total, class: "form-control shadow rounded" %>
    </div>
  </div>

  


  <div class="form-group row">
    <%= form.label :category, class: "col-2 col-form-label text-light" %>
    <div class="col-10">
    <%= form.collection_select(:category_id, Category.all, :id, :name,
                               { prompt: "Make your selections from the list below (can be empty)" }, { size: 5, class: "custom-select shadow rounded" }) %>
    </div>
  </div>

<div class="form-group row">
    <%= form.label :vendor, class: "col-2 col-form-label text-light" %>
    <div class="col-10">
    <%= form.collection_select(:vendor_ids, Vendor.all, :id, :name,
                               { prompt: "Make your selections from the list below (can be empty)" }, { multiple: true, size: 5, class: "custom-select shadow rounded" }) %>
    </div>
  </div>
 
 
<div class="form-group row justify-content-center">
    <%= form.submit class: "btn btn-outline-light btn-lg" %>
</div>
<% end %>
</div>

<%= link_to "[ Cancel and return to product listing ]", products_path, class: "text-info" %>
</div>

</div>

app/views/products/_history.erb
<table class="table table-bordered">
  <thead class="thead-light">
    <tr>
      <th scope="col">change of quantity</th>
      <th scope="col">date</th>
      <th scope="col">action</th>

    </tr>
  </thead>
  <tbody>
  <% @productHistory.each do |productHistory| %>
    <tr>
      <th scope="row" class="text-center"><%= productHistory.change_in_quantity %></th>
      <td><%= productHistory.created_at.in_time_zone("America/Chicago").strftime("%m/%d/%Y %H:%M%p") %></td>
      <td></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/products/_product.html.erb
<% # <div class="row p-4"> %>
<% # <div class="col-1"> %>

<% # <%= render "filter" %>
<% # </div> %>

<div class="pl-5 pr-5">
<table class="table table-hover table-bordered table-light">
  <thead>
    <tr>
      <th scope="col">Instance_id</th>
      <th scope="col">Name</th>
      <th scope="col">Foreign Name</th>
      <th scope="col">Barcode</th>
      <th scope="col">Quantity</th>
      <th scope="col">Category</th>
      <th scope="col">Expiration Date</th>
      <th scope="col">Updated Date</th>

      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
  <% @products.each do |product| %>
    <tr>
    <td><%= product.instance_id %></td>
      <td class="text-capitalize"><%= link_to product.name, product_path(product) %></td>
      <td><%= product.foreign_name %></td>
      <td><%= product.barcode %></td>
      <td><%= product.quantity_in_total %></td>
       <td>  <%= product.category.name %></td>

       <td><%= product.expiration_date.in_time_zone("America/Chicago").strftime("%m/%d/%Y") %>
      <td><%= product.updated_at.in_time_zone("America/Chicago").strftime("%m/%d/%Y - %H:%M:%S") %></td>
<td>
<%= link_to "Edit", edit_product_path(product), class: "btn btn-outline-info text-center " %>
    <%= link_to "Delete", product_path(product), class: "btn btn-outline-danger text-center ", method: :delete, data: { confirm: "Are you sure?" } %></td></td>
    </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>

app/views/products/edit.html.erb
<h1 class="text-center">
    Edit product
</h1>
<%= render "form" %>

app/views/products/index.html.erb
<div class="pl-2 pr-2">
<div class="d-flex justify-content-between align-items-center">
<h1 >Product Listing: <%= @products.count %></h1>
<div class="d-flex ">
<%= link_to "New product", new_product_path, class: "btn btn-outline-info mr-2" %>
<%= link_to "Back to homepage", root_path, class: "btn btn-outline-secondary" %>
</div>
</div>

<table class="table table-striped table-bordered table-light">
  <thead>
    <tr>
      <th scope="col">Id</th>
      <th scope="col">Name</th>
      <th scope="col">Foreign Name</th>
      <th scope="col">Barcode</th>
      <th scope="col">Quantity</th>
      <th scope="col">Category</th>
      <th scope="col">Vendors</th>
      <th scope="col">Expiration Date</th>
      <th scope="col">Updated Date</th>

      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
  <% @products.each do |product| %>
    <tr>
    <td><%= product.instance_id %></td>
      <td class="text-capitalize"><%= link_to product.name, product_path(product) %></td>
      <td><%= product.foreign_name %></td>
      <td><%= product.barcode %></td>
      <td><%= product.quantity_in_total %></td>
      <% if product.category %>
       <td>  <%= link_to product.category.name, category_path(product.category) %></td>
       <% else %>
        <td>no</td>
      <% end %></td>

       <% if product.vendors.any? %>
              <td><%= render product.vendors %></td> 
               <% else %>
               <td></td>
            <% end %>
       <td><%= product.expiration_date.strftime("%m/%d/%Y") %>
        <td><%= product.updated_at.in_time_zone("America/Chicago").strftime("%m/%d/%Y%H:%M:%S%P") %></td>
  <td><%= link_to "Edit", edit_product_path(product), class: "btn btn-outline-info text-center btn-sm " %>
    <%= link_to "Delete", product_path(product), class: "btn btn-outline-danger text-center btn-sm ", method: :delete, data: { confirm: "Are you sure?" } %></td></td>
    </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>

app/views/products/new.html.erb
<h1 class="text-center">
    Create new product
</h1>
<%= render "form" %>

<div class="position-absolute closed" style="width:100%; height:100%; top:0;z-index:-1">
<div class="scanner position-absolute d-none" style="top:14.7%;left:25%; width:50%; height:50%;">

</div>
</div>

app/views/products/show.html.erb
<div class="pl-2 pr-2">
<%= link_to "back to product list", products_path, class: "btn btn-outline-secondary float-right mt-4 mb-2" %>
<table class="table table-striped table-bordered table-light">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Foreign Name</th>
      <th scope="col">Barcode</th>
 
 
      <th scope="col">Quantity</th>
      <th scope="col">Category</th>
      <th scope="col">Vendors</th>
      <th scope="col">Expiration Date</th>
      <th scope="col">Created Date</th>

      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td class="text-capitalize"><%= @product.name %></td>
      <td><%= @product.foreign_name %></td>
      <td><%= @product.barcode %></td>

    
      <td><%= @product.quantity_in_total %></td>
      <% if @product.category %>
       <td>  <%= @product.category.name %></td>
       <% else %>
        <td>None</td>
      <% end %></td>

       <% if @product.vendors.any? %>
              <td><%= render @product.vendors %></td> 
               <% else %>
               <td></td>
            <% end %>
       <td><%= @product.expiration_date.strftime("%m/%d/%Y") %>
      <td><%= @product.created_at.strftime("%m/%d/%Y") %></td>
      <td>   <%= link_to "Edit", edit_product_path(@product), class: "btn btn-outline-info text-center " %>
    <%= link_to "Delete", product_path(@product), class: "btn btn-outline-danger text-center ", method: :delete, data: { confirm: "Are you sure?" } %></td>
    </tr>
  </tbody>
</table>


<div class="row">
<div class="col-sm">
<%= render "history" %>
</div>

<div class="col-sm">

</div>
<div class="col-sm">

</div>

</div>



</div>







 