config/routes.rb
Rails.application.routes.draw do
  root "homepage#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # resources :articles, only: [:show, :index, :new, :create,:edit, :update,:destroy]
  resources :articles
  resources :products
  resources :sales
  get "signup", to: "users#new"
  resources :users, except: [:new]
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  resources :categories
  resources :product_lists
  resources :shipments
  resources :vendors
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true
  validates :text, presence: true
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  validates_uniqueness_of :name
  has_many :article_categories
  has_many :articles, through: :article_categories
  has_many :products
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :product_histories
  has_many :product_vendors
  has_many :vendors, through: :product_vendors

  def self.filter(params)
    if params.length > 3
      puts "filtered"
      params.slice(0, params.length - 3)
      products = Category.find_by(name: "Frozen").products
      return products
    else
      puts "all"
      products = Product.all
      return products
    end
  end

  def barcode=(value)
    if value.length == 12
      write_attribute(:barcode, value.insert(0, "0"))
    else
      write_attribute(:barcode, value)
    end
  end

   def self.to_csv
    attributes = %w{id name quantity_in_total}

    CSV.generate(headers: true) do |csv|
      csv << attributes

      all.each do |user|
        csv << attributes.map{ |attr| user.send(attr) }
      end
    end
  end

   
end

app/models/product_history.rb
class ProductHistory < ApplicationRecord
  belongs_to :product
end

app/models/product_list.rb
class ProductList < ApplicationRecord
   
end

app/models/product_vendor.rb
class ProductVendor < ApplicationRecord
  belongs_to :product
  belongs_to :vendor
end

app/models/sale.rb
class Sale < ApplicationRecord
  validates :data, presence: true
end

app/models/shipment.rb
class Shipment < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  has_many :articles, dependent: :destroy
  validates :username, presence: true, length: { minimum: 3, maximum: 25 }, uniqueness: { case_sensitive: false }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 105 }, uniqueness: { case_sensitive: false }, format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/models/vendor.rb
class Vendor < ApplicationRecord
  has_many :product_vendors
  has_many :products, through: :product_vendors
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = { size: 80 })
    email_address = user.email
    hash = Digest::MD5.hexdigest(email_address)
    size = options[:size]
    image_src = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(image_src, alt: user.username, class: "rounded mx-auto d-block shadow")
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/shipments_helper.rb
module ShipmentsHelper
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-4 bg-dark text-white">
    <div class="container text-center">
 
    </div>
  </footer>

app/views/layouts/_jumbotron.html.erb
 <div id="home-container" class="container">
      <div class="jumbotron text-center text-white">
        <h1 class="display-4">Alpha Blog</h1>
        <p class="lead">
          This is a simple hero unit, a simple jumbotron-style component for
          calling extra attention to featured content or information.
        </p>
        <hr class="my-4" />
        <p>
          It uses utility classes for typography and spacing to space content
          out within the larger container.
        </p>

        <%= link_to "Sign Up", signup_path, class: "btn btn-success btn-lg" %>
      </div>
    </div>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %> 
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar bg-dark fixed-top navbar-dark flex-md-nowrap p-0 shadow">
      <%= link_to "Inventory System", root_path, class: "navbar-brand col-sm-3 col-md-2 mr-0", id: "logo" %>
   

      <input type="text" class="form-control form-control-dark w-100" placeholder="Search" aria-label="Search">
      <ul class="class navbar-nav px-3">
      <li class="nav-item text-nowrap">
      <% # <a href="" class="nav-link">Sign out</a> %>
     <% if logged_in? %>
           <li class="nav-item">
            <li class="nav-item dropdown">
            <a
              class="nav-link dropdown-toggle text-info"
              href="#"
              id="navbarDropdown"
              role="button"
              data-toggle="dropdown"
              aria-haspopup="true"
              aria-expanded="false"
            >
              <%= "(Admin)" if current_user.admin? %> Profiles [<%= current_user.username %>]
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            
              <%= link_to "View your profile", user_path(current_user), class: "dropdown-item" %>
            
              <%= link_to "Edit your profile", edit_user_path(current_user), class: "dropdown-item" %>
               <%= link_to "Log out", logout_path, method: :delete, class: "dropdown-item text-danger" %>
  
          
          </li>
         
          </li>
          <% else %>
        
           <%= link_to "Log in", login_path, class: "nav-link text-info font-weight-bold" %>
           
        
          </li>
         
          <% end %>


      </li>
      </ul>
    </nav>



    

app/views/layouts/_sidebar.html.erb
  <div class="sidebar-sticky">
    <ul class="nav flex-column">
       
 
  <li class="nav-item" >

           <a  class="nav-link" href=<%= categories_path %>><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file-text"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline><line x1="16" y1="13" x2="8" y2="13"></line><line x1="16" y1="17" x2="8" y2="17"></line><polyline points="10 9 9 9 8 9"></polyline></svg>
           Category
           </a>
          </li>

    <li class="nav-item" >

           <a  class="nav-link" href=<%= products_path %>><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file-text"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline><line x1="16" y1="13" x2="8" y2="13"></line><line x1="16" y1="17" x2="8" y2="17"></line><polyline points="10 9 9 9 8 9"></polyline></svg>
           Products
           </a>
          </li>
          <li class="nav-item" >

           <a  class="nav-link" href=<%= vendors_path %>><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file-text"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline><line x1="16" y1="13" x2="8" y2="13"></line><line x1="16" y1="17" x2="8" y2="17"></line><polyline points="10 9 9 9 8 9"></polyline></svg>
           Vendor
           </a>
          </li>
          <li class="nav-item" >

           <a  class="nav-link" href=<%= shipments_path %>><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file-text"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline><line x1="16" y1="13" x2="8" y2="13"></line><line x1="16" y1="17" x2="8" y2="17"></line><polyline points="10 9 9 9 8 9"></polyline></svg>
           Orders
           </a>
          </li>
          <li class="nav-item" >

           <a  class="nav-link" href=<%= sales_path %>><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file-text"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline><line x1="16" y1="13" x2="8" y2="13"></line><line x1="16" y1="17" x2="8" y2="17"></line><polyline points="10 9 9 9 8 9"></polyline></svg>
           Sales
           </a>
          </li>
        </ul>
  </div>

        
 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Demo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", 'data-turbolinks-track': "reload" %>
    <%= javascript_pack_tag "application", 'data-turbolinks-track': "reload" %>
  </head>

  <body>
   
   <%= render "layouts/navigation" %>

  <div class="container-fluid">
  <div class="row">
  <nav class="col-md-2 d-md-block bg-light sidebar">
  <%= render "layouts/sidebar" %>
  </nav>
   <main class="col-md-9 ml-sm-auto col-lg-10 pt-5">
   <%= render "layouts/messages" %>
     <%= yield %>
  </main>
  </div>
  </div>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<div class="alert alert-danger alert-dismissible fade show" role="alert">
  <h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase %> from being saved</h4>
  <ul>
<% obj.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
  <% end %>
</ul>
 <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<% end %>